########## REDE / STREAMING ##########
cache=yes
cache-secs=300
demuxer-readahead-secs=60
demuxer-max-bytes=1024MiB

########## ÁUDIO ##########
audio-buffer=2.0

########## VÍDEO ##########
vo=gpu
gpu-api=opengl

########## HW DECODING ##########
hwdec=auto-safe

######### IDIOMA ########
alang=ja,jpn
slang=eng,en

##### SEMPRE SOBRE AS OUTRAS JANELAS #######
ontop=yes

#YT
ytdl-format=bestvideo[height<=720]+bestaudio/best
